[project]
name = "foresight"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "alembic>=1.16.5",
  "fastapi>=0.117.1",
  "pydantic>=2.11.9",
  "pydantic-settings>=2.11.0",
  "python-jose[cryptography]>=3.5.0",
  "passlib>=1.7.4",
  "sqlalchemy>=2.0.43",
  "uvicorn>=0.37.0",
  "argon2-cffi>=25.1.0",
  "python-multipart>=0.0.20",
  "email-validator>=2.3.0",
  "psycopg2-binary>=2.9.11",
  "sqlalchemy-cockroachdb>=2.0.3",
]

[dependency-groups]
dev = [
  "httpx>=0.28.1",
  "ipython>=9.5.0",
  "mypy>=1.18.2",
  "mypy-extensions>=1.1.0",
  "pytest>=8.4.2",
  "pytest-cov>=7.0.0",
  "ruff>=0.14.4",
  "types-passlib>=1.7.7.20250602",
  "types-python-jose>=3.5.0.20250531",
]

# ------------------------------------------------------
# Mypy
# ------------------------------------------------------

[tool.mypy]
python_version = "3.13"
check_untyped_defs = true
disallow_untyped_defs = false
explicit_package_bases = true
ignore_missing_imports = true
namespace_packages = true
warn_unused_configs = true
exclude = [
  "alembic/versions",
]

# ------------------------------------------------------
# Ruff
# ------------------------------------------------------

[tool.ruff]
line-length = 88
target-version = "py313"

[tool.ruff.lint]
# E: pycodestyle errors
# F: Pyflakes
# I: isort (ordenação de imports)
# W: pycodestyle warnings
select = ["E", "F", "I", "W"]
ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

# ------------------------------------------------------
# Pylint
# ------------------------------------------------------

[tool.pylint.main]
py-version = "3.13"
jobs = 0
ignore-patterns = ["test_.*\\.py"]
extension-pkg-allow-list = ["pyodbc"]

[tool.pylint.messages_control]
disable = [
  "too-few-public-methods",
  "duplicate-code",
  "missing-module-docstring",
]

[tool.pylint.basic]
# Permite:
# - _ (descartáveis)
# - i, j, k (loops)
# - TEntity, TId, TSearch (Type Parameters - PEP 695)
good-names-rgx = "^(_|i|j|k|T[A-Z][a-zA-Z0-9]*)$"
argument-naming-style = "snake_case"
attr-naming-style = "snake_case"
function-naming-style = "snake_case"
method-naming-style = "snake_case"
variable-naming-style = "snake_case"
class-naming-style = "PascalCase"
const-naming-style = "UPPER_CASE"

[tool.pylint.design]
min-public-methods = 1
max-attributes = 30

[tool.pylint.typecheck]
ignore-none = true
ignore-mixin-members = true

[tool.pylint.format]
max-line-length = 88

[tool.pylint.reports]
reports = false
output-format = "colorized"

# ------------------------------------------------------
# Pytest
# ------------------------------------------------------

[tool.pytest.ini_options]
pythonpath = "."
python_files = "tests.py tests_*.py *_tests.py test_*.py *_test.py"
addopts = "-v --import-mode=importlib"
testpaths = "tests"
filterwarnings = [
  "ignore:Cannot correctly sort tables:sqlalchemy.exc.SAWarning",
  "ignore:Accessing argon2.__version__:DeprecationWarning",
  "ignore:pandas only supports SQLAlchemy connectable:UserWarning",
  "ignore:The behavior of DataFrame concatenation:FutureWarning",
  "ignore::ResourceWarning",
]
