[pytest]
pythonpath = .
python_files = tests.py test_*.py *_tests.py
addopts = --import-mode=importlib
testpaths = tests
filterwarnings =
    # Ignora o aviso de ciclo de tabelas do SQLAlchemy (específico dos testes)
    ignore:Cannot correctly sort tables:sqlalchemy.exc.SAWarning
    # Ignora o aviso da passlib
    ignore:Accessing argon2.__version__:DeprecationWarning
