"""add unique constraint code_tenant_id to org_units

Revision ID: 2bed7f135cf3
Revises: 3c06c5788579
Create Date: 2025-12-08 18:48:41.191735

"""

from typing import Sequence, Union


from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2bed7f135cf3"
down_revision: Union[str, Sequence[str], None] = "3c06c5788579"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organizational_units", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("uq_organizational_units_code"),
            ["code", "tenant_id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organizational_units", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_organizational_units_code"),
            type_="unique",
        )

    # ### end Alembic commands ###
