"""created sqlalchemy mixins and applied at tables

Revision ID: 45094001b7fb
Revises: c70dd18950e1
Create Date: 2025-11-07 20:27:52.844974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.shared_kernel.infrastructure.config.custom_types import GUID_Type

# revision identifiers, used by Alembic.
revision: str = '45094001b7fb'
down_revision: Union[str, Sequence[str], None] = 'c70dd18950e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('deleted_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_areas_is_active'), postgresql_ops={'is_active': None}, postgresql_using='prefix')
        batch_op.create_index(batch_op.f('ix_areas_is_active'), ['is_active'], unique=False)
        batch_op.drop_index(batch_op.f('ix_areas_tenant_id'), postgresql_ops={'tenant_id': None}, postgresql_using='prefix')
        batch_op.create_index(batch_op.f('ix_areas_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('organizational_units', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('deleted_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_organizational_units_is_active'), postgresql_ops={'is_active': None}, postgresql_using='prefix')
        batch_op.create_index(batch_op.f('ix_organizational_units_is_active'), ['is_active'], unique=False)
        batch_op.drop_index(batch_op.f('ix_organizational_units_tenant_id'), postgresql_ops={'tenant_id': None}, postgresql_using='prefix')
        batch_op.create_index(batch_op.f('ix_organizational_units_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_permissions_codename'), postgresql_ops={'codename': None}, postgresql_using='prefix')
        batch_op.create_index(batch_op.f('ix_permissions_codename'), ['codename'], unique=True)

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', GUID_Type(), nullable=True))
        batch_op.add_column(sa.Column('updated_by', GUID_Type(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_roles_name'), postgresql_ops={'name': None}, postgresql_using='prefix')
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)
        batch_op.drop_index(batch_op.f('ix_roles_tenant_id'), postgresql_ops={'tenant_id': None}, postgresql_using='prefix')
        batch_op.create_index(batch_op.f('ix_roles_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('deleted_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_users_email'), postgresql_ops={'email': None}, postgresql_using='prefix')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.drop_index(batch_op.f('ix_users_is_active'), postgresql_ops={'is_active': None}, postgresql_using='prefix')
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'), postgresql_ops={'tenant_id': None}, postgresql_using='prefix')
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), [sa.literal_column('tenant_id NULLS FIRST')], unique=False, postgresql_ops={'tenant_id': None}, postgresql_using='prefix')
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.create_index(batch_op.f('ix_users_is_active'), [sa.literal_column('is_active NULLS FIRST')], unique=False, postgresql_ops={'is_active': None}, postgresql_using='prefix')
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('ix_users_email'), [sa.literal_column('email NULLS FIRST')], unique=True, postgresql_ops={'email': None}, postgresql_using='prefix')
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_tenant_id'))
        batch_op.create_index(batch_op.f('ix_roles_tenant_id'), [sa.literal_column('tenant_id NULLS FIRST')], unique=False, postgresql_ops={'tenant_id': None}, postgresql_using='prefix')
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.create_index(batch_op.f('ix_roles_name'), [sa.literal_column('name NULLS FIRST')], unique=True, postgresql_ops={'name': None}, postgresql_using='prefix')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_codename'))
        batch_op.create_index(batch_op.f('ix_permissions_codename'), [sa.literal_column('codename NULLS FIRST')], unique=True, postgresql_ops={'codename': None}, postgresql_using='prefix')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('organizational_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizational_units_tenant_id'))
        batch_op.create_index(batch_op.f('ix_organizational_units_tenant_id'), [sa.literal_column('tenant_id NULLS FIRST')], unique=False, postgresql_ops={'tenant_id': None}, postgresql_using='prefix')
        batch_op.drop_index(batch_op.f('ix_organizational_units_is_active'))
        batch_op.create_index(batch_op.f('ix_organizational_units_is_active'), [sa.literal_column('is_active NULLS FIRST')], unique=False, postgresql_ops={'is_active': None}, postgresql_using='prefix')
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_areas_tenant_id'))
        batch_op.create_index(batch_op.f('ix_areas_tenant_id'), [sa.literal_column('tenant_id NULLS FIRST')], unique=False, postgresql_ops={'tenant_id': None}, postgresql_using='prefix')
        batch_op.drop_index(batch_op.f('ix_areas_is_active'))
        batch_op.create_index(batch_op.f('ix_areas_is_active'), [sa.literal_column('is_active NULLS FIRST')], unique=False, postgresql_ops={'is_active': None}, postgresql_using='prefix')
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    # ### end Alembic commands ###
