"""add soft delete to user

Revision ID: 5882c102c84e
Revises: a2e45a10db5b
Create Date: 2025-10-20 20:23:28.289374

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5882c102c84e"
down_revision: Union[str, Sequence[str], None] = "a2e45a10db5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.create_index(op.f("ix_users_is_active"), "users", ["is_active"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_is_active"), table_name="users")
    op.drop_column("users", "deleted_at")
    # ### end Alembic commands ###
