"""update unique constraint on exchange rates to include date

Revision ID: 664c42d17cd4
Revises: 6402c584295b
Create Date: 2026-05-10 20:20:42.830161

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "664c42d17cd4"
down_revision: str | Sequence[str] | None = "6402c584295b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("areas", schema=None) as batch_op:
        batch_op.alter_column(
            "deleted_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )
        batch_op.drop_index(
            batch_op.f("ix_areas_is_active"),
            postgresql_ops={"is_active": None},
            postgresql_using="prefix",
        )
        batch_op.create_index(
            batch_op.f("ix_areas_is_active"), ["is_active"], unique=False
        )
        batch_op.drop_index(
            batch_op.f("ix_areas_tenant_id"),
            postgresql_ops={"tenant_id": None},
            postgresql_using="prefix",
        )
        batch_op.create_index(
            batch_op.f("ix_areas_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("exchange_rates", schema=None) as batch_op:
        if op.get_bind().dialect.name == "sqlite":
            batch_op.drop_constraint("uq_scenario_exchange_rate", type_="unique")
        else:
            batch_op.execute(
                "DROP INDEX exchange_rates@uq_scenario_exchange_rate CASCADE"
            )
        batch_op.create_unique_constraint(
            "uq_scenario_exchange_rate",
            ["scenario_id", "from_currency", "to_currency", "effective_date"],
        )

    with op.batch_alter_table("organizational_units", schema=None) as batch_op:
        batch_op.alter_column(
            "deleted_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )
        batch_op.drop_index(
            batch_op.f("ix_organizational_units_is_active"),
            postgresql_ops={"is_active": None},
            postgresql_using="prefix",
        )
        batch_op.create_index(
            batch_op.f("ix_organizational_units_is_active"), ["is_active"], unique=False
        )
        batch_op.drop_index(
            batch_op.f("ix_organizational_units_tenant_id"),
            postgresql_ops={"tenant_id": None},
            postgresql_using="prefix",
        )
        batch_op.create_index(
            batch_op.f("ix_organizational_units_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_permissions_codename"),
            postgresql_ops={"codename": None},
            postgresql_using="prefix",
        )
        batch_op.create_index(
            batch_op.f("ix_permissions_codename"), ["codename"], unique=True
        )

    with op.batch_alter_table("plans", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )

    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.alter_column(
            "deleted_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )
        batch_op.drop_index(
            batch_op.f("ix_roles_is_active"),
            postgresql_ops={"is_active": None},
            postgresql_using="prefix",
        )
        batch_op.create_index(
            batch_op.f("ix_roles_is_active"), ["is_active"], unique=False
        )
        batch_op.drop_index(
            batch_op.f("ix_roles_name"),
            postgresql_ops={"name": None},
            postgresql_using="prefix",
        )
        batch_op.create_index(batch_op.f("ix_roles_name"), ["name"], unique=False)
        batch_op.drop_index(
            batch_op.f("ix_roles_tenant_id"),
            postgresql_ops={"tenant_id": None},
            postgresql_using="prefix",
        )
        batch_op.create_index(
            batch_op.f("ix_roles_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("scenarios", schema=None) as batch_op:
        batch_op.alter_column(
            "deleted_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )
        batch_op.drop_index(
            batch_op.f("ix_scenarios_is_active"),
            postgresql_ops={"is_active": None},
            postgresql_using="prefix",
        )
        batch_op.create_index(
            batch_op.f("ix_scenarios_is_active"), ["is_active"], unique=False
        )
        batch_op.drop_index(
            batch_op.f("ix_scenarios_tenant_id"),
            postgresql_ops={"tenant_id": None},
            postgresql_using="prefix",
        )
        batch_op.create_index(
            batch_op.f("ix_scenarios_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("tenants", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "deleted_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )
        batch_op.drop_index(
            batch_op.f("ix_users_email"),
            postgresql_ops={"email": None},
            postgresql_using="prefix",
        )
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.drop_index(
            batch_op.f("ix_users_is_active"),
            postgresql_ops={"is_active": None},
            postgresql_using="prefix",
        )
        batch_op.create_index(
            batch_op.f("ix_users_is_active"), ["is_active"], unique=False
        )
        batch_op.drop_index(
            batch_op.f("ix_users_tenant_id"),
            postgresql_ops={"tenant_id": None},
            postgresql_using="prefix",
        )
        batch_op.create_index(
            batch_op.f("ix_users_tenant_id"), ["tenant_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_tenant_id"))
        batch_op.create_index(
            batch_op.f("ix_users_tenant_id"),
            [sa.literal_column("tenant_id NULLS FIRST")],
            unique=False,
            postgresql_ops={"tenant_id": None},
            postgresql_using="prefix",
        )
        batch_op.drop_index(batch_op.f("ix_users_is_active"))
        batch_op.create_index(
            batch_op.f("ix_users_is_active"),
            [sa.literal_column("is_active NULLS FIRST")],
            unique=False,
            postgresql_ops={"is_active": None},
            postgresql_using="prefix",
        )
        batch_op.drop_index(batch_op.f("ix_users_email"))
        batch_op.create_index(
            batch_op.f("ix_users_email"),
            [sa.literal_column("email NULLS FIRST")],
            unique=True,
            postgresql_ops={"email": None},
            postgresql_using="prefix",
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "deleted_at",
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )

    with op.batch_alter_table("tenants", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )

    with op.batch_alter_table("scenarios", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scenarios_tenant_id"))
        batch_op.create_index(
            batch_op.f("ix_scenarios_tenant_id"),
            [sa.literal_column("tenant_id NULLS FIRST")],
            unique=False,
            postgresql_ops={"tenant_id": None},
            postgresql_using="prefix",
        )
        batch_op.drop_index(batch_op.f("ix_scenarios_is_active"))
        batch_op.create_index(
            batch_op.f("ix_scenarios_is_active"),
            [sa.literal_column("is_active NULLS FIRST")],
            unique=False,
            postgresql_ops={"is_active": None},
            postgresql_using="prefix",
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "deleted_at",
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )

    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_roles_tenant_id"))
        batch_op.create_index(
            batch_op.f("ix_roles_tenant_id"),
            [sa.literal_column("tenant_id NULLS FIRST")],
            unique=False,
            postgresql_ops={"tenant_id": None},
            postgresql_using="prefix",
        )
        batch_op.drop_index(batch_op.f("ix_roles_name"))
        batch_op.create_index(
            batch_op.f("ix_roles_name"),
            [sa.literal_column("name NULLS FIRST")],
            unique=False,
            postgresql_ops={"name": None},
            postgresql_using="prefix",
        )
        batch_op.drop_index(batch_op.f("ix_roles_is_active"))
        batch_op.create_index(
            batch_op.f("ix_roles_is_active"),
            [sa.literal_column("is_active NULLS FIRST")],
            unique=False,
            postgresql_ops={"is_active": None},
            postgresql_using="prefix",
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "deleted_at",
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )

    with op.batch_alter_table("plans", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )

    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_permissions_codename"))
        batch_op.create_index(
            batch_op.f("ix_permissions_codename"),
            [sa.literal_column("codename NULLS FIRST")],
            unique=True,
            postgresql_ops={"codename": None},
            postgresql_using="prefix",
        )

    with op.batch_alter_table("organizational_units", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organizational_units_tenant_id"))
        batch_op.create_index(
            batch_op.f("ix_organizational_units_tenant_id"),
            [sa.literal_column("tenant_id NULLS FIRST")],
            unique=False,
            postgresql_ops={"tenant_id": None},
            postgresql_using="prefix",
        )
        batch_op.drop_index(batch_op.f("ix_organizational_units_is_active"))
        batch_op.create_index(
            batch_op.f("ix_organizational_units_is_active"),
            [sa.literal_column("is_active NULLS FIRST")],
            unique=False,
            postgresql_ops={"is_active": None},
            postgresql_using="prefix",
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "deleted_at",
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )

    with op.batch_alter_table("exchange_rates", schema=None) as batch_op:
        if op.get_bind().dialect.name == "sqlite":
            batch_op.drop_constraint("uq_scenario_exchange_rate", type_="unique")
        else:
            batch_op.execute(
                "DROP INDEX exchange_rates@uq_scenario_exchange_rate CASCADE"
            )
        batch_op.create_unique_constraint(
            batch_op.f("uq_scenario_exchange_rate"),
            ["scenario_id", "from_currency", "to_currency"],
            postgresql_nulls_not_distinct=False,
        )

    with op.batch_alter_table("areas", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_areas_tenant_id"))
        batch_op.create_index(
            batch_op.f("ix_areas_tenant_id"),
            [sa.literal_column("tenant_id NULLS FIRST")],
            unique=False,
            postgresql_ops={"tenant_id": None},
            postgresql_using="prefix",
        )
        batch_op.drop_index(batch_op.f("ix_areas_is_active"))
        batch_op.create_index(
            batch_op.f("ix_areas_is_active"),
            [sa.literal_column("is_active NULLS FIRST")],
            unique=False,
            postgresql_ops={"is_active": None},
            postgresql_using="prefix",
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "deleted_at",
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
