"""add soft delete to areas

Revision ID: a2e45a10db5b
Revises: a51e0dcb0bc1
Create Date: 2025-10-20 20:18:11.862080

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a2e45a10db5b"
down_revision: Union[str, Sequence[str], None] = "a51e0dcb0bc1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("areas", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column("areas", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.create_index(op.f("ix_areas_is_active"), "areas", ["is_active"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_areas_is_active"), table_name="areas")
    op.drop_column("areas", "deleted_at")
    op.drop_column("areas", "is_active")
    # ### end Alembic commands ###
