"""add created_at and updated_at to role

Revision ID: a60181f2c9a1
Revises: 2d9ccdb042f5
Create Date: 2025-09-30 18:52:18.870075

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a60181f2c9a1"
down_revision: Union[str, Sequence[str], None] = "2d9ccdb042f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("roles", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("roles", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("roles", "updated_at")
    op.drop_column("roles", "created_at")
    # ### end Alembic commands ###
