"""add tenant_id to all tables

Revision ID: c70dd18950e1
Revises: 5fb7c3322f1b
Create Date: 2025-11-04 20:43:05.335565

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from src.shared_kernel.infrastructure.config.custom_types import GUID_Type

# revision identifiers, used by Alembic.
revision: str = "c70dd18950e1"
down_revision: Union[str, Sequence[str], None] = "5fb7c3322f1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("areas", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", GUID_Type(), nullable=False))
        batch_op.drop_index(
            batch_op.f("ix_areas_is_active"),
            postgresql_ops={"is_active": None},
            postgresql_using="prefix",
        )
        batch_op.create_index(
            batch_op.f("ix_areas_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_areas_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_foreign_key(None, "tenants", ["tenant_id"], ["id"])

    with op.batch_alter_table("organizational_units", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", GUID_Type(), nullable=False))
        batch_op.drop_index(
            batch_op.f("ix_organizational_units_is_active"),
            postgresql_ops={"is_active": None},
            postgresql_using="prefix",
        )
        batch_op.create_index(
            batch_op.f("ix_organizational_units_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_organizational_units_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_foreign_key(None, "tenants", ["tenant_id"], ["id"])

    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_permissions_codename"),
            postgresql_ops={"codename": None},
            postgresql_using="prefix",
        )
        batch_op.create_index(
            batch_op.f("ix_permissions_codename"), ["codename"], unique=True
        )

    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", GUID_Type(), nullable=False))
        batch_op.drop_index(
            batch_op.f("ix_roles_name"),
            postgresql_ops={"name": None},
            postgresql_using="prefix",
        )
        batch_op.create_index(batch_op.f("ix_roles_name"), ["name"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_roles_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_foreign_key(None, "tenants", ["tenant_id"], ["id"])

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", GUID_Type(), nullable=True))
        batch_op.drop_index(
            batch_op.f("ix_users_email"),
            postgresql_ops={"email": None},
            postgresql_using="prefix",
        )
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.drop_index(
            batch_op.f("ix_users_is_active"),
            postgresql_ops={"is_active": None},
            postgresql_using="prefix",
        )
        batch_op.create_index(
            batch_op.f("ix_users_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_users_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_foreign_key(None, "tenants", ["tenant_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_users_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_users_is_active"))
        batch_op.create_index(
            batch_op.f("ix_users_is_active"),
            [sa.literal_column("is_active NULLS FIRST")],
            unique=False,
            postgresql_ops={"is_active": None},
            postgresql_using="prefix",
        )
        batch_op.drop_index(batch_op.f("ix_users_email"))
        batch_op.create_index(
            batch_op.f("ix_users_email"),
            [sa.literal_column("email NULLS FIRST")],
            unique=True,
            postgresql_ops={"email": None},
            postgresql_using="prefix",
        )
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_roles_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_roles_name"))
        batch_op.create_index(
            batch_op.f("ix_roles_name"),
            [sa.literal_column("name NULLS FIRST")],
            unique=True,
            postgresql_ops={"name": None},
            postgresql_using="prefix",
        )
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_permissions_codename"))
        batch_op.create_index(
            batch_op.f("ix_permissions_codename"),
            [sa.literal_column("codename NULLS FIRST")],
            unique=True,
            postgresql_ops={"codename": None},
            postgresql_using="prefix",
        )

    with op.batch_alter_table("organizational_units", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_organizational_units_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_organizational_units_is_active"))
        batch_op.create_index(
            batch_op.f("ix_organizational_units_is_active"),
            [sa.literal_column("is_active NULLS FIRST")],
            unique=False,
            postgresql_ops={"is_active": None},
            postgresql_using="prefix",
        )
        batch_op.drop_column("tenant_id")

    with op.batch_alter_table("areas", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_areas_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_areas_is_active"))
        batch_op.create_index(
            batch_op.f("ix_areas_is_active"),
            [sa.literal_column("is_active NULLS FIRST")],
            unique=False,
            postgresql_ops={"is_active": None},
            postgresql_using="prefix",
        )
        batch_op.drop_column("tenant_id")

    # ### end Alembic commands ###
