"""Initial schema with custom type GUID_Type

Revision ID: c7d2845c7011
Revises:
Create Date: 2025-10-31 19:41:54.463259

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from src.core.infrastructure.config import GUID_Type

# revision identifiers, used by Alembic.
revision: str = "c7d2845c7011"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "areas",
        sa.Column("id", GUID_Type(), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("areas", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_areas_is_active"), ["is_active"], unique=False
        )

    op.create_table(
        "organizational_units",
        sa.Column("id", GUID_Type(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=False),
        sa.Column("parent_id", GUID_Type(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["organizational_units.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("organizational_units", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_organizational_units_is_active"), ["is_active"], unique=False
        )

    op.create_table(
        "permissions",
        sa.Column("id", GUID_Type(), nullable=False),
        sa.Column("codename", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_permissions_codename"), ["codename"], unique=True
        )

    op.create_table(
        "roles",
        sa.Column("id", GUID_Type(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_roles_name"), ["name"], unique=True)

    op.create_table(
        "users",
        sa.Column("id", GUID_Type(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_users_is_active"), ["is_active"], unique=False
        )

    op.create_table(
        "role_permissions",
        sa.Column("role_id", GUID_Type(), nullable=False),
        sa.Column("permission_id", GUID_Type(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "user_permissions",
        sa.Column("user_id", GUID_Type(), nullable=False),
        sa.Column("permission_id", GUID_Type(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "permission_id"),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", GUID_Type(), nullable=False),
        sa.Column("role_id", GUID_Type(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_roles")
    op.drop_table("user_permissions")
    op.drop_table("role_permissions")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_is_active"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_roles_name"))

    op.drop_table("roles")
    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_permissions_codename"))

    op.drop_table("permissions")
    with op.batch_alter_table("organizational_units", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organizational_units_is_active"))

    op.drop_table("organizational_units")
    with op.batch_alter_table("areas", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_areas_is_active"))

    op.drop_table("areas")
    # ### end Alembic commands ###
